# Generated by Django 3.1.1 on 2021-05-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
